# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'base' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for base

   pod 'GoogleSignIn'
   pod 'Firebase/Core', '4.0.0'
   pod 'FirebaseMessaging'
  target 'base-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'baseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
