export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_FIREBASE_SUCCESS = 'LOGIN_FIREBASE_SUCCESS'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const LOGIN_USER_CANCELLED = 'LOGIN_USER_CANCELLED'

export const FETCHING_TOKEN = 'FETCHING_TOKEN'
export const TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND'
export const TOKEN_NOT_VALID = 'TOKEN_NOT_VALID'

export const REFRESH_CURRENT_USER = 'REFRESH_CURRENT_USER'

export const FCM_TOKEN = 'FCM_TOKEN'

export const USER_LIST_UPDATED = "USER_LIST_UPDATED"
export const USER_LIST_FETCHING = "USER_LIST_FETCHING"

export const CURRENT_USER_TOKEN = "CURRENT_USER_TOKEN"

export const NETWORK_ERROR = "NETWORK_ERROR"

export const SUGGESTION_LIST_UPDATED= "SUGGESTION_LIST_UPDATED"
export const SUGGESTION_LIST_FETCHING= "SUGGESTION_LIST_FETCHING"