export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_FIREBASE_SUCCESS = 'LOGIN_FIREBASE_SUCCESS'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const LOGIN_USER_CANCELLED = 'LOGIN_USER_CANCELLED'

export const FETCHING_TOKEN = 'FETCHING_TOKEN'
export const TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND'
export const TOKEN_NOT_VALID = 'TOKEN_NOT_VALID'

export const REFRESH_CURRENT_USER = 'REFRESH_CURRENT_USER'

export const FCM_TOKEN = 'FCM_TOKEN'